// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace showtime{
export enum ValueType{
  NONE= 0,
  INT= 1,
  FLOAT= 2,
  STRING= 3
}};

/**
 * @enum {number}
 */
export namespace showtime{
export enum ValueList{
  NONE= 0,
  IntList= 1,
  FloatList= 2,
  StrList= 3
}};

/**
 * @enum {number}
 */
export namespace showtime{
export enum PlugDirection{
  NONE= 0,
  IN_JACK= 1,
  OUT_JACK= 2
}};

/**
 * @enum {number}
 */
export namespace showtime{
export enum EntityTypes{
  NONE= 0,
  Component= 1,
  Performer= 2,
  Plug= 3,
  Factory= 4
}};

/**
 * @constructor
 */
export namespace showtime{
export class IntList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns IntList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):IntList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param IntList= obj
 * @returns IntList
 */
static getRootAsIntList(bb:flatbuffers.ByteBuffer, obj?:IntList):IntList {
  return (obj || new IntList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
val(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns number
 */
valLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Int32Array
 */
valArray():Int32Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startIntList(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valOffset
 */
static addVal(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createValVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startValVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endIntList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createIntList(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset):flatbuffers.Offset {
  IntList.startIntList(builder);
  IntList.addVal(builder, valOffset);
  return IntList.endIntList(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class FloatList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FloatList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FloatList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FloatList= obj
 * @returns FloatList
 */
static getRootAsFloatList(bb:flatbuffers.ByteBuffer, obj?:FloatList):FloatList {
  return (obj || new FloatList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
val(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
};

/**
 * @returns number
 */
valLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Float32Array
 */
valArray():Float32Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFloatList(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valOffset
 */
static addVal(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createValVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startValVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFloatList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFloatList(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset):flatbuffers.Offset {
  FloatList.startFloatList(builder);
  FloatList.addVal(builder, valOffset);
  return FloatList.endFloatList(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class StrList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StrList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StrList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StrList= obj
 * @returns StrList
 */
static getRootAsStrList(bb:flatbuffers.ByteBuffer, obj?:StrList):StrList {
  return (obj || new StrList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
val(index: number):string
val(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
val(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
valLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startStrList(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valOffset
 */
static addVal(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createValVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startValVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStrList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createStrList(builder:flatbuffers.Builder, valOffset:flatbuffers.Offset):flatbuffers.Offset {
  StrList.startStrList(builder);
  StrList.addVal(builder, valOffset);
  return StrList.endStrList(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class PlugValue {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns PlugValue
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlugValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param PlugValue= obj
 * @returns PlugValue
 */
static getRootAsPlugValue(bb:flatbuffers.ByteBuffer, obj?:PlugValue):PlugValue {
  return (obj || new PlugValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns showtime.ValueList
 */
valuesType():showtime.ValueList {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : showtime.ValueList.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
values<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPlugValue(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param showtime.ValueList valuesType
 */
static addValuesType(builder:flatbuffers.Builder, valuesType:showtime.ValueList) {
  builder.addFieldInt8(0, valuesType, showtime.ValueList.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valuesOffset
 */
static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valuesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPlugValue(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPlugValue(builder:flatbuffers.Builder, valuesType:showtime.ValueList, valuesOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlugValue.startPlugValue(builder);
  PlugValue.addValuesType(builder, valuesType);
  PlugValue.addValues(builder, valuesOffset);
  return PlugValue.endPlugValue(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityData= obj
 * @returns EntityData
 */
static getRootAsEntityData(bb:flatbuffers.ByteBuffer, obj?:EntityData):EntityData {
  return (obj || new EntityData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
URI():string|null
URI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
URI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
owner():string|null
owner(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
owner(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityData(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset URIOffset
 */
static addURI(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, URIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset ownerOffset
 */
static addOwner(builder:flatbuffers.Builder, ownerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, ownerOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityData(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset, ownerOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityData.startEntityData(builder);
  EntityData.addURI(builder, URIOffset);
  EntityData.addOwner(builder, ownerOffset);
  return EntityData.endEntityData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ComponentData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ComponentData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ComponentData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ComponentData= obj
 * @returns ComponentData
 */
static getRootAsComponentData(bb:flatbuffers.ByteBuffer, obj?:ComponentData):ComponentData {
  return (obj || new ComponentData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
componentType():string|null
componentType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
componentType(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startComponentData(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset componentTypeOffset
 */
static addComponentType(builder:flatbuffers.Builder, componentTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, componentTypeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endComponentData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createComponentData(builder:flatbuffers.Builder, componentTypeOffset:flatbuffers.Offset):flatbuffers.Offset {
  ComponentData.startComponentData(builder);
  ComponentData.addComponentType(builder, componentTypeOffset);
  return ComponentData.endComponentData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class PerformerData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns PerformerData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PerformerData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param PerformerData= obj
 * @returns PerformerData
 */
static getRootAsPerformerData(bb:flatbuffers.ByteBuffer, obj?:PerformerData):PerformerData {
  return (obj || new PerformerData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startPerformerData(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPerformerData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPerformerData(builder:flatbuffers.Builder):flatbuffers.Offset {
  PerformerData.startPerformerData(builder);
  return PerformerData.endPerformerData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class PlugData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns PlugData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):PlugData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param PlugData= obj
 * @returns PlugData
 */
static getRootAsPlugData(bb:flatbuffers.ByteBuffer, obj?:PlugData):PlugData {
  return (obj || new PlugData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns showtime.PlugDirection
 */
plugDirection():showtime.PlugDirection {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : showtime.PlugDirection.NONE;
};

/**
 * @returns number
 */
maxCables():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param showtime.PlugValue= obj
 * @returns showtime.PlugValue|null
 */
value(obj?:showtime.PlugValue):showtime.PlugValue|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new showtime.PlugValue).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPlugData(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param showtime.PlugDirection plugDirection
 */
static addPlugDirection(builder:flatbuffers.Builder, plugDirection:showtime.PlugDirection) {
  builder.addFieldInt8(0, plugDirection, showtime.PlugDirection.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param number maxCables
 */
static addMaxCables(builder:flatbuffers.Builder, maxCables:number) {
  builder.addFieldInt32(1, maxCables, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valueOffset
 */
static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valueOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPlugData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPlugData(builder:flatbuffers.Builder, plugDirection:showtime.PlugDirection, maxCables:number, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlugData.startPlugData(builder);
  PlugData.addPlugDirection(builder, plugDirection);
  PlugData.addMaxCables(builder, maxCables);
  PlugData.addValue(builder, valueOffset);
  return PlugData.endPlugData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class FactoryData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FactoryData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FactoryData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FactoryData= obj
 * @returns FactoryData
 */
static getRootAsFactoryData(bb:flatbuffers.ByteBuffer, obj?:FactoryData):FactoryData {
  return (obj || new FactoryData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
creatables(index: number):string
creatables(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
creatables(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
creatablesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFactoryData(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset creatablesOffset
 */
static addCreatables(builder:flatbuffers.Builder, creatablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, creatablesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCreatablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCreatablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFactoryData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFactoryData(builder:flatbuffers.Builder, creatablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  FactoryData.startFactoryData(builder);
  FactoryData.addCreatables(builder, creatablesOffset);
  return FactoryData.endFactoryData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Entity {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Entity
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Entity {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Entity= obj
 * @returns Entity
 */
static getRootAsEntity(bb:flatbuffers.ByteBuffer, obj?:Entity):Entity {
  return (obj || new Entity).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.EntityData= obj
 * @returns showtime.EntityData|null
 */
entity(obj?:showtime.EntityData):showtime.EntityData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.EntityData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntity(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entityOffset
 */
static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntity(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset):flatbuffers.Offset {
  Entity.startEntity(builder);
  Entity.addEntity(builder, entityOffset);
  return Entity.endEntity(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Component {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Component
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Component {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Component= obj
 * @returns Component
 */
static getRootAsComponent(bb:flatbuffers.ByteBuffer, obj?:Component):Component {
  return (obj || new Component).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.EntityData= obj
 * @returns showtime.EntityData|null
 */
entity(obj?:showtime.EntityData):showtime.EntityData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.EntityData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.ComponentData= obj
 * @returns showtime.ComponentData|null
 */
component(obj?:showtime.ComponentData):showtime.ComponentData|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new showtime.ComponentData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startComponent(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entityOffset
 */
static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset componentOffset
 */
static addComponent(builder:flatbuffers.Builder, componentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, componentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createComponent(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset, componentOffset:flatbuffers.Offset):flatbuffers.Offset {
  Component.startComponent(builder);
  Component.addEntity(builder, entityOffset);
  Component.addComponent(builder, componentOffset);
  return Component.endComponent(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Performer {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Performer
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Performer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Performer= obj
 * @returns Performer
 */
static getRootAsPerformer(bb:flatbuffers.ByteBuffer, obj?:Performer):Performer {
  return (obj || new Performer).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.EntityData= obj
 * @returns showtime.EntityData|null
 */
entity(obj?:showtime.EntityData):showtime.EntityData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.EntityData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.ComponentData= obj
 * @returns showtime.ComponentData|null
 */
component(obj?:showtime.ComponentData):showtime.ComponentData|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new showtime.ComponentData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.PerformerData= obj
 * @returns showtime.PerformerData|null
 */
performer(obj?:showtime.PerformerData):showtime.PerformerData|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new showtime.PerformerData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPerformer(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entityOffset
 */
static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset componentOffset
 */
static addComponent(builder:flatbuffers.Builder, componentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, componentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset performerOffset
 */
static addPerformer(builder:flatbuffers.Builder, performerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, performerOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPerformer(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPerformer(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset, componentOffset:flatbuffers.Offset, performerOffset:flatbuffers.Offset):flatbuffers.Offset {
  Performer.startPerformer(builder);
  Performer.addEntity(builder, entityOffset);
  Performer.addComponent(builder, componentOffset);
  Performer.addPerformer(builder, performerOffset);
  return Performer.endPerformer(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Plug {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Plug
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Plug {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Plug= obj
 * @returns Plug
 */
static getRootAsPlug(bb:flatbuffers.ByteBuffer, obj?:Plug):Plug {
  return (obj || new Plug).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.EntityData= obj
 * @returns showtime.EntityData|null
 */
entity(obj?:showtime.EntityData):showtime.EntityData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.EntityData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.PlugData= obj
 * @returns showtime.PlugData|null
 */
plug(obj?:showtime.PlugData):showtime.PlugData|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new showtime.PlugData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startPlug(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entityOffset
 */
static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset plugOffset
 */
static addPlug(builder:flatbuffers.Builder, plugOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, plugOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endPlug(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createPlug(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset, plugOffset:flatbuffers.Offset):flatbuffers.Offset {
  Plug.startPlug(builder);
  Plug.addEntity(builder, entityOffset);
  Plug.addPlug(builder, plugOffset);
  return Plug.endPlug(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Factory {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Factory
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Factory {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Factory= obj
 * @returns Factory
 */
static getRootAsFactory(bb:flatbuffers.ByteBuffer, obj?:Factory):Factory {
  return (obj || new Factory).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.EntityData= obj
 * @returns showtime.EntityData|null
 */
entity(obj?:showtime.EntityData):showtime.EntityData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.EntityData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.FactoryData= obj
 * @returns showtime.FactoryData|null
 */
factory(obj?:showtime.FactoryData):showtime.FactoryData|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new showtime.FactoryData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFactory(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entityOffset
 */
static addEntity(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, entityOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset factoryOffset
 */
static addFactory(builder:flatbuffers.Builder, factoryOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, factoryOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFactory(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFactory(builder:flatbuffers.Builder, entityOffset:flatbuffers.Offset, factoryOffset:flatbuffers.Offset):flatbuffers.Offset {
  Factory.startFactory(builder);
  Factory.addEntity(builder, entityOffset);
  Factory.addFactory(builder, factoryOffset);
  return Factory.endFactory(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class CableData {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CableData
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CableData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CableData= obj
 * @returns CableData
 */
static getRootAsCableData(bb:flatbuffers.ByteBuffer, obj?:CableData):CableData {
  return (obj || new CableData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
inputURI():string|null
inputURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
inputURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
outputURI():string|null
outputURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
outputURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCableData(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset inputURIOffset
 */
static addInputURI(builder:flatbuffers.Builder, inputURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inputURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset outputURIOffset
 */
static addOutputURI(builder:flatbuffers.Builder, outputURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, outputURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCableData(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCableData(builder:flatbuffers.Builder, inputURIOffset:flatbuffers.Offset, outputURIOffset:flatbuffers.Offset):flatbuffers.Offset {
  CableData.startCableData(builder);
  CableData.addInputURI(builder, inputURIOffset);
  CableData.addOutputURI(builder, outputURIOffset);
  return CableData.endCableData(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class Cable {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Cable
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Cable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Cable= obj
 * @returns Cable
 */
static getRootAsCable(bb:flatbuffers.ByteBuffer, obj?:Cable):Cable {
  return (obj || new Cable).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.CableData= obj
 * @returns showtime.CableData|null
 */
address(obj?:showtime.CableData):showtime.CableData|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new showtime.CableData).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCable(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset addressOffset
 */
static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, addressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCable(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCable(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset):flatbuffers.Offset {
  Cable.startCable(builder);
  Cable.addAddress(builder, addressOffset);
  return Cable.endCable(builder);
}
}
}
