// automatically generated by the FlatBuffers compiler, do not modify

import * as NS10296227678231156406 from "./graph_types_generated";
/**
 * @constructor
 */
export namespace showtime{
export class GraphMessage {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GraphMessage
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GraphMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GraphMessage= obj
 * @returns GraphMessage
 */
static getRootAsGraphMessage(bb:flatbuffers.ByteBuffer, obj?:GraphMessage):GraphMessage {
  return (obj || new GraphMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
sender():string|null
sender(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sender(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param showtime.PlugValue= obj
 * @returns showtime.PlugValue|null
 */
value(obj?:NS10296227678231156406.showtime.PlugValue):NS10296227678231156406.showtime.PlugValue|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS10296227678231156406.showtime.PlugValue).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startGraphMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset senderOffset
 */
static addSender(builder:flatbuffers.Builder, senderOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, senderOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset valueOffset
 */
static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGraphMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishGraphMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

static createGraphMessage(builder:flatbuffers.Builder, senderOffset:flatbuffers.Offset, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  GraphMessage.startGraphMessage(builder);
  GraphMessage.addSender(builder, senderOffset);
  GraphMessage.addValue(builder, valueOffset);
  return GraphMessage.endGraphMessage(builder);
}
}
}
