// automatically generated by the FlatBuffers compiler, do not modify

import * as NS10296227678231156406 from "./graph_types_generated";
/**
 * @enum {number}
 */
export namespace showtime{
export enum Signal{
  EMPTY= 0,
  OK= 1,
  CLIENT_SYNC= 2,
  CLIENT_HEARTBEAT= 3,
  ERR_MSG_TYPE_UNKNOWN= 4,
  ERR_STAGE_BAD_CABLE_DISCONNECT_REQUEST= 5,
  ERR_STAGE_BAD_CABLE_CONNECT_REQUEST= 6,
  ERR_STAGE_PERFORMER_NOT_FOUND= 7,
  ERR_STAGE_PERFORMER_ALREADY_EXISTS= 8,
  ERR_STAGE_PERFORMER_ALREADY_CONNECTED= 9,
  ERR_STAGE_REQUEST_MISSING_ARG= 10,
  ERR_ENTITY_NOT_FOUND= 11,
  ERR_ENTITY_ALREADY_EXISTS= 12,
  ERR_CABLE_PLUGS_NOT_FOUND= 13,
  ERR_STAGE_TIMEOUT= 14,
  ERR_NOT_CONNECTED= 15
}};

/**
 * @enum {number}
 */
export namespace showtime{
export enum ClientLeaveReason{
  QUIT= 0,
  TIMEOUT= 1,
  CRASH= 2
}};

/**
 * @enum {number}
 */
export namespace showtime{
export enum Content{
  NONE= 0,
  SignalMessage= 1,
  ClientJoinRequest= 2,
  ClientLeaveRequest= 3,
  ClientGraphHandshakeStart= 4,
  ClientGraphHandshakeStop= 5,
  ClientGraphHandshakeListen= 6,
  EntityCreateRequest= 7,
  EntityReadRequest= 8,
  EntityUpdateRequest= 9,
  EntityDestroyRequest= 10,
  EntityTakeOwnershipRequest= 11,
  EntityObserveRequest= 12,
  FactoryCreateEntityRequest= 13,
  CableCreateRequest= 14,
  CableReadRequest= 15,
  CableUpdateRequest= 16,
  CableDestroyRequest= 17
}};

/**
 * @constructor
 */
export namespace showtime{
export class SignalMessage {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SignalMessage
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SignalMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SignalMessage= obj
 * @returns SignalMessage
 */
static getRootAsSignalMessage(bb:flatbuffers.ByteBuffer, obj?:SignalMessage):SignalMessage {
  return (obj || new SignalMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns showtime.Signal
 */
signal():showtime.Signal {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : showtime.Signal.EMPTY;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSignalMessage(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param showtime.Signal signal
 */
static addSignal(builder:flatbuffers.Builder, signal:showtime.Signal) {
  builder.addFieldInt8(0, signal, showtime.Signal.EMPTY);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSignalMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSignalMessage(builder:flatbuffers.Builder, signal:showtime.Signal):flatbuffers.Offset {
  SignalMessage.startSignalMessage(builder);
  SignalMessage.addSignal(builder, signal);
  return SignalMessage.endSignalMessage(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ClientJoinRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientJoinRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientJoinRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientJoinRequest= obj
 * @returns ClientJoinRequest
 */
static getRootAsClientJoinRequest(bb:flatbuffers.ByteBuffer, obj?:ClientJoinRequest):ClientJoinRequest {
  return (obj || new ClientJoinRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.Performer= obj
 * @returns showtime.Performer|null
 */
performer(obj?:NS10296227678231156406.showtime.Performer):NS10296227678231156406.showtime.Performer|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS10296227678231156406.showtime.Performer).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphReliableAddress():string|null
graphReliableAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphReliableAddress(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
graphUnreliableAddress():string|null
graphUnreliableAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
graphUnreliableAddress(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientJoinRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset performerOffset
 */
static addPerformer(builder:flatbuffers.Builder, performerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, performerOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphReliableAddressOffset
 */
static addGraphReliableAddress(builder:flatbuffers.Builder, graphReliableAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, graphReliableAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset graphUnreliableAddressOffset
 */
static addGraphUnreliableAddress(builder:flatbuffers.Builder, graphUnreliableAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, graphUnreliableAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientJoinRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientJoinRequest(builder:flatbuffers.Builder, performerOffset:flatbuffers.Offset, graphReliableAddressOffset:flatbuffers.Offset, graphUnreliableAddressOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientJoinRequest.startClientJoinRequest(builder);
  ClientJoinRequest.addPerformer(builder, performerOffset);
  ClientJoinRequest.addGraphReliableAddress(builder, graphReliableAddressOffset);
  ClientJoinRequest.addGraphUnreliableAddress(builder, graphUnreliableAddressOffset);
  return ClientJoinRequest.endClientJoinRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ClientGraphHandshakeStart {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientGraphHandshakeStart
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientGraphHandshakeStart {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientGraphHandshakeStart= obj
 * @returns ClientGraphHandshakeStart
 */
static getRootAsClientGraphHandshakeStart(bb:flatbuffers.ByteBuffer, obj?:ClientGraphHandshakeStart):ClientGraphHandshakeStart {
  return (obj || new ClientGraphHandshakeStart).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
receiverURI():string|null
receiverURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
receiverURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
receiverAddress():string|null
receiverAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
receiverAddress(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientGraphHandshakeStart(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset receiverURIOffset
 */
static addReceiverURI(builder:flatbuffers.Builder, receiverURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, receiverURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset receiverAddressOffset
 */
static addReceiverAddress(builder:flatbuffers.Builder, receiverAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, receiverAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientGraphHandshakeStart(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientGraphHandshakeStart(builder:flatbuffers.Builder, receiverURIOffset:flatbuffers.Offset, receiverAddressOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientGraphHandshakeStart.startClientGraphHandshakeStart(builder);
  ClientGraphHandshakeStart.addReceiverURI(builder, receiverURIOffset);
  ClientGraphHandshakeStart.addReceiverAddress(builder, receiverAddressOffset);
  return ClientGraphHandshakeStart.endClientGraphHandshakeStart(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ClientGraphHandshakeStop {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientGraphHandshakeStop
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientGraphHandshakeStop {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientGraphHandshakeStop= obj
 * @returns ClientGraphHandshakeStop
 */
static getRootAsClientGraphHandshakeStop(bb:flatbuffers.ByteBuffer, obj?:ClientGraphHandshakeStop):ClientGraphHandshakeStop {
  return (obj || new ClientGraphHandshakeStop).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
receiverURI():string|null
receiverURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
receiverURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientGraphHandshakeStop(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset receiverURIOffset
 */
static addReceiverURI(builder:flatbuffers.Builder, receiverURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, receiverURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientGraphHandshakeStop(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientGraphHandshakeStop(builder:flatbuffers.Builder, receiverURIOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientGraphHandshakeStop.startClientGraphHandshakeStop(builder);
  ClientGraphHandshakeStop.addReceiverURI(builder, receiverURIOffset);
  return ClientGraphHandshakeStop.endClientGraphHandshakeStop(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ClientGraphHandshakeListen {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientGraphHandshakeListen
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientGraphHandshakeListen {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientGraphHandshakeListen= obj
 * @returns ClientGraphHandshakeListen
 */
static getRootAsClientGraphHandshakeListen(bb:flatbuffers.ByteBuffer, obj?:ClientGraphHandshakeListen):ClientGraphHandshakeListen {
  return (obj || new ClientGraphHandshakeListen).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
senderURI():string|null
senderURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
senderURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
senderAddress():string|null
senderAddress(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
senderAddress(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientGraphHandshakeListen(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset senderURIOffset
 */
static addSenderURI(builder:flatbuffers.Builder, senderURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, senderURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset senderAddressOffset
 */
static addSenderAddress(builder:flatbuffers.Builder, senderAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, senderAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientGraphHandshakeListen(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientGraphHandshakeListen(builder:flatbuffers.Builder, senderURIOffset:flatbuffers.Offset, senderAddressOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientGraphHandshakeListen.startClientGraphHandshakeListen(builder);
  ClientGraphHandshakeListen.addSenderURI(builder, senderURIOffset);
  ClientGraphHandshakeListen.addSenderAddress(builder, senderAddressOffset);
  return ClientGraphHandshakeListen.endClientGraphHandshakeListen(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class ClientLeaveRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ClientLeaveRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ClientLeaveRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ClientLeaveRequest= obj
 * @returns ClientLeaveRequest
 */
static getRootAsClientLeaveRequest(bb:flatbuffers.ByteBuffer, obj?:ClientLeaveRequest):ClientLeaveRequest {
  return (obj || new ClientLeaveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
performerURI():string|null
performerURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
performerURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns showtime.ClientLeaveReason
 */
reason():showtime.ClientLeaveReason {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readInt8(this.bb_pos + offset)) : showtime.ClientLeaveReason.QUIT;
};

/**
 * @param flatbuffers.Builder builder
 */
static startClientLeaveRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset performerURIOffset
 */
static addPerformerURI(builder:flatbuffers.Builder, performerURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, performerURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param showtime.ClientLeaveReason reason
 */
static addReason(builder:flatbuffers.Builder, reason:showtime.ClientLeaveReason) {
  builder.addFieldInt8(1, reason, showtime.ClientLeaveReason.QUIT);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endClientLeaveRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createClientLeaveRequest(builder:flatbuffers.Builder, performerURIOffset:flatbuffers.Offset, reason:showtime.ClientLeaveReason):flatbuffers.Offset {
  ClientLeaveRequest.startClientLeaveRequest(builder);
  ClientLeaveRequest.addPerformerURI(builder, performerURIOffset);
  ClientLeaveRequest.addReason(builder, reason);
  return ClientLeaveRequest.endClientLeaveRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityCreateRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityCreateRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityCreateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityCreateRequest= obj
 * @returns EntityCreateRequest
 */
static getRootAsEntityCreateRequest(bb:flatbuffers.ByteBuffer, obj?:EntityCreateRequest):EntityCreateRequest {
  return (obj || new EntityCreateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns showtime.EntityTypes
 */
entitiesType(index: number):showtime.EntityTypes|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)) : /**  */ (0);
};

/**
 * @returns number
 */
entitiesTypeLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
entitiesTypeArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @param flatbuffers.Table= obj
 * @returns ?flatbuffers.Table
 */
entities<T extends flatbuffers.Table>(index: number, obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
};

/**
 * @returns number
 */
entitiesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityCreateRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entitiesTypeOffset
 */
static addEntitiesType(builder:flatbuffers.Builder, entitiesTypeOffset:NS10296227678231156406.flatbuffers.Offset) {
  builder.addFieldOffset(0, entitiesTypeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<showtime.EntityTypes> data
 * @returns flatbuffers.Offset
 */
static createEntitiesTypeVector(builder:flatbuffers.Builder, data:showtime.EntityTypes[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startEntitiesTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entitiesOffset
 */
static addEntities(builder:flatbuffers.Builder, entitiesOffset:NS10296227678231156406.flatbuffers.Offset) {
  builder.addFieldOffset(1, entitiesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityCreateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityCreateRequest(builder:flatbuffers.Builder, entitiesTypeOffset:NS10296227678231156406.flatbuffers.Offset, entitiesOffset:NS10296227678231156406.flatbuffers.Offset):flatbuffers.Offset {
  EntityCreateRequest.startEntityCreateRequest(builder);
  EntityCreateRequest.addEntitiesType(builder, entitiesTypeOffset);
  EntityCreateRequest.addEntities(builder, entitiesOffset);
  return EntityCreateRequest.endEntityCreateRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityReadRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityReadRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityReadRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityReadRequest= obj
 * @returns EntityReadRequest
 */
static getRootAsEntityReadRequest(bb:flatbuffers.ByteBuffer, obj?:EntityReadRequest):EntityReadRequest {
  return (obj || new EntityReadRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
URI():string|null
URI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
URI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityReadRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset URIOffset
 */
static addURI(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, URIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityReadRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityReadRequest(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityReadRequest.startEntityReadRequest(builder);
  EntityReadRequest.addURI(builder, URIOffset);
  return EntityReadRequest.endEntityReadRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityUpdateRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityUpdateRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityUpdateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityUpdateRequest= obj
 * @returns EntityUpdateRequest
 */
static getRootAsEntityUpdateRequest(bb:flatbuffers.ByteBuffer, obj?:EntityUpdateRequest):EntityUpdateRequest {
  return (obj || new EntityUpdateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns showtime.EntityTypes
 */
entitiesType(index: number):showtime.EntityTypes|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index)) : /**  */ (0);
};

/**
 * @returns number
 */
entitiesTypeLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
entitiesTypeArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @param flatbuffers.Table= obj
 * @returns ?flatbuffers.Table
 */
entities<T extends flatbuffers.Table>(index: number, obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
};

/**
 * @returns number
 */
entitiesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityUpdateRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entitiesTypeOffset
 */
static addEntitiesType(builder:flatbuffers.Builder, entitiesTypeOffset:NS10296227678231156406.flatbuffers.Offset) {
  builder.addFieldOffset(0, entitiesTypeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<showtime.EntityTypes> data
 * @returns flatbuffers.Offset
 */
static createEntitiesTypeVector(builder:flatbuffers.Builder, data:showtime.EntityTypes[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startEntitiesTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset entitiesOffset
 */
static addEntities(builder:flatbuffers.Builder, entitiesOffset:NS10296227678231156406.flatbuffers.Offset) {
  builder.addFieldOffset(1, entitiesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createEntitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startEntitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityUpdateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityUpdateRequest(builder:flatbuffers.Builder, entitiesTypeOffset:NS10296227678231156406.flatbuffers.Offset, entitiesOffset:NS10296227678231156406.flatbuffers.Offset):flatbuffers.Offset {
  EntityUpdateRequest.startEntityUpdateRequest(builder);
  EntityUpdateRequest.addEntitiesType(builder, entitiesTypeOffset);
  EntityUpdateRequest.addEntities(builder, entitiesOffset);
  return EntityUpdateRequest.endEntityUpdateRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityDestroyRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityDestroyRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityDestroyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityDestroyRequest= obj
 * @returns EntityDestroyRequest
 */
static getRootAsEntityDestroyRequest(bb:flatbuffers.ByteBuffer, obj?:EntityDestroyRequest):EntityDestroyRequest {
  return (obj || new EntityDestroyRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
URI():string|null
URI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
URI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityDestroyRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset URIOffset
 */
static addURI(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, URIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityDestroyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityDestroyRequest(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityDestroyRequest.startEntityDestroyRequest(builder);
  EntityDestroyRequest.addURI(builder, URIOffset);
  return EntityDestroyRequest.endEntityDestroyRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityTakeOwnershipRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityTakeOwnershipRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityTakeOwnershipRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityTakeOwnershipRequest= obj
 * @returns EntityTakeOwnershipRequest
 */
static getRootAsEntityTakeOwnershipRequest(bb:flatbuffers.ByteBuffer, obj?:EntityTakeOwnershipRequest):EntityTakeOwnershipRequest {
  return (obj || new EntityTakeOwnershipRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
URI():string|null
URI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
URI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
newOwner():string|null
newOwner(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
newOwner(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityTakeOwnershipRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset URIOffset
 */
static addURI(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, URIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset newOwnerOffset
 */
static addNewOwner(builder:flatbuffers.Builder, newOwnerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, newOwnerOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityTakeOwnershipRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityTakeOwnershipRequest(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset, newOwnerOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityTakeOwnershipRequest.startEntityTakeOwnershipRequest(builder);
  EntityTakeOwnershipRequest.addURI(builder, URIOffset);
  EntityTakeOwnershipRequest.addNewOwner(builder, newOwnerOffset);
  return EntityTakeOwnershipRequest.endEntityTakeOwnershipRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class EntityObserveRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EntityObserveRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EntityObserveRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EntityObserveRequest= obj
 * @returns EntityObserveRequest
 */
static getRootAsEntityObserveRequest(bb:flatbuffers.ByteBuffer, obj?:EntityObserveRequest):EntityObserveRequest {
  return (obj || new EntityObserveRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
URI():string|null
URI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
URI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEntityObserveRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset URIOffset
 */
static addURI(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, URIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEntityObserveRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEntityObserveRequest(builder:flatbuffers.Builder, URIOffset:flatbuffers.Offset):flatbuffers.Offset {
  EntityObserveRequest.startEntityObserveRequest(builder);
  EntityObserveRequest.addURI(builder, URIOffset);
  return EntityObserveRequest.endEntityObserveRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class FactoryCreateEntityRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns FactoryCreateEntityRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):FactoryCreateEntityRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param FactoryCreateEntityRequest= obj
 * @returns FactoryCreateEntityRequest
 */
static getRootAsFactoryCreateEntityRequest(bb:flatbuffers.ByteBuffer, obj?:FactoryCreateEntityRequest):FactoryCreateEntityRequest {
  return (obj || new FactoryCreateEntityRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
creatableEntityURI():string|null
creatableEntityURI(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
creatableEntityURI(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startFactoryCreateEntityRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset creatableEntityURIOffset
 */
static addCreatableEntityURI(builder:flatbuffers.Builder, creatableEntityURIOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, creatableEntityURIOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endFactoryCreateEntityRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createFactoryCreateEntityRequest(builder:flatbuffers.Builder, creatableEntityURIOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  FactoryCreateEntityRequest.startFactoryCreateEntityRequest(builder);
  FactoryCreateEntityRequest.addCreatableEntityURI(builder, creatableEntityURIOffset);
  FactoryCreateEntityRequest.addName(builder, nameOffset);
  return FactoryCreateEntityRequest.endFactoryCreateEntityRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class CableCreateRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CableCreateRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CableCreateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CableCreateRequest= obj
 * @returns CableCreateRequest
 */
static getRootAsCableCreateRequest(bb:flatbuffers.ByteBuffer, obj?:CableCreateRequest):CableCreateRequest {
  return (obj || new CableCreateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param showtime.Cable= obj
 * @returns showtime.Cable
 */
cables(index: number, obj?:NS10296227678231156406.showtime.Cable):NS10296227678231156406.showtime.Cable|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS10296227678231156406.showtime.Cable).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
cablesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCableCreateRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cablesOffset
 */
static addCables(builder:flatbuffers.Builder, cablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cablesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCableCreateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCableCreateRequest(builder:flatbuffers.Builder, cablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  CableCreateRequest.startCableCreateRequest(builder);
  CableCreateRequest.addCables(builder, cablesOffset);
  return CableCreateRequest.endCableCreateRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class CableReadRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CableReadRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CableReadRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CableReadRequest= obj
 * @returns CableReadRequest
 */
static getRootAsCableReadRequest(bb:flatbuffers.ByteBuffer, obj?:CableReadRequest):CableReadRequest {
  return (obj || new CableReadRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.Cable= obj
 * @returns showtime.Cable|null
 */
address(obj?:NS10296227678231156406.showtime.Cable):NS10296227678231156406.showtime.Cable|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS10296227678231156406.showtime.Cable).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCableReadRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset addressOffset
 */
static addAddress(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, addressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCableReadRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCableReadRequest(builder:flatbuffers.Builder, addressOffset:flatbuffers.Offset):flatbuffers.Offset {
  CableReadRequest.startCableReadRequest(builder);
  CableReadRequest.addAddress(builder, addressOffset);
  return CableReadRequest.endCableReadRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class CableUpdateRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CableUpdateRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CableUpdateRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CableUpdateRequest= obj
 * @returns CableUpdateRequest
 */
static getRootAsCableUpdateRequest(bb:flatbuffers.ByteBuffer, obj?:CableUpdateRequest):CableUpdateRequest {
  return (obj || new CableUpdateRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param showtime.Cable= obj
 * @returns showtime.Cable|null
 */
oldAddress(obj?:NS10296227678231156406.showtime.Cable):NS10296227678231156406.showtime.Cable|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS10296227678231156406.showtime.Cable).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param showtime.Cable= obj
 * @returns showtime.Cable|null
 */
newAddress(obj?:NS10296227678231156406.showtime.Cable):NS10296227678231156406.showtime.Cable|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS10296227678231156406.showtime.Cable).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCableUpdateRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset oldAddressOffset
 */
static addOldAddress(builder:flatbuffers.Builder, oldAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, oldAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset newAddressOffset
 */
static addNewAddress(builder:flatbuffers.Builder, newAddressOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, newAddressOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCableUpdateRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCableUpdateRequest(builder:flatbuffers.Builder, oldAddressOffset:flatbuffers.Offset, newAddressOffset:flatbuffers.Offset):flatbuffers.Offset {
  CableUpdateRequest.startCableUpdateRequest(builder);
  CableUpdateRequest.addOldAddress(builder, oldAddressOffset);
  CableUpdateRequest.addNewAddress(builder, newAddressOffset);
  return CableUpdateRequest.endCableUpdateRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class CableDestroyRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CableDestroyRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CableDestroyRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CableDestroyRequest= obj
 * @returns CableDestroyRequest
 */
static getRootAsCableDestroyRequest(bb:flatbuffers.ByteBuffer, obj?:CableDestroyRequest):CableDestroyRequest {
  return (obj || new CableDestroyRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param showtime.Cable= obj
 * @returns showtime.Cable
 */
cables(index: number, obj?:NS10296227678231156406.showtime.Cable):NS10296227678231156406.showtime.Cable|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS10296227678231156406.showtime.Cable).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
cablesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCableDestroyRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset cablesOffset
 */
static addCables(builder:flatbuffers.Builder, cablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cablesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createCablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startCablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCableDestroyRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCableDestroyRequest(builder:flatbuffers.Builder, cablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  CableDestroyRequest.startCableDestroyRequest(builder);
  CableDestroyRequest.addCables(builder, cablesOffset);
  return CableDestroyRequest.endCableDestroyRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace showtime{
export class StageMessage {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns StageMessage
 */
__init(i:number, bb:flatbuffers.ByteBuffer):StageMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param StageMessage= obj
 * @returns StageMessage
 */
static getRootAsStageMessage(bb:flatbuffers.ByteBuffer, obj?:StageMessage):StageMessage {
  return (obj || new StageMessage).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns showtime.Content
 */
contentType():showtime.Content {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : showtime.Content.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
content<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @returns flatbuffers.Long
 */
id():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Builder builder
 */
static startStageMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param showtime.Content contentType
 */
static addContentType(builder:flatbuffers.Builder, contentType:showtime.Content) {
  builder.addFieldInt8(0, contentType, showtime.Content.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset contentOffset
 */
static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long id
 */
static addId(builder:flatbuffers.Builder, id:flatbuffers.Long) {
  builder.addFieldInt64(2, id, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endStageMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishStageMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

static createStageMessage(builder:flatbuffers.Builder, contentType:showtime.Content, contentOffset:flatbuffers.Offset, id:flatbuffers.Long):flatbuffers.Offset {
  StageMessage.startStageMessage(builder);
  StageMessage.addContentType(builder, contentType);
  StageMessage.addContent(builder, contentOffset);
  StageMessage.addId(builder, id);
  return StageMessage.endStageMessage(builder);
}
}
}
